spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/1023067718/Spring-Cloud-Config.git
          search-paths: respo
          username: *
          password: *
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411

#springCloudConfig的端口号默认8888，不能再application.yaml中修改，需要在bootstrap.properties中修改(优先于application配置文件)
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/